package speech

import (
	"html"
	"regexp"
	"strings"
	"unicode/utf8"
)

var (
	garbageRE  = regexp.MustCompile(`(?is)<(?:script|style|head)[^>]*>.*?</(?:script|style|head)>`)
	anchorRE   = regexp.MustCompile(`(?is)<a[^>]*href=["'][^"']+["'][^>]*>(.*?)</a>`)
	tagRE      = regexp.MustCompile(`(?is)<[^>]+>`)
	spaceRE    = regexp.MustCompile(`[ \t\r\n]+`)
	urlRE      = regexp.MustCompile(`(?i)\bhttps?://[^\s<>]+`)
	emailRE    = regexp.MustCompile(`(?i)\b[A-Z0-9._%+\-]+@[A-Z0-9.\-]+\.[A-Z]{2,}\b`)
	percentRE  = regexp.MustCompile(`\b(\d+(?:\.\d+)?)%`)
	currencyRE = regexp.MustCompile(`([$€££])\s?(\d+(?:[.,]\d{1,2})?)`)
	phoneRE    = regexp.MustCompile(`(?:\+?\d[\d .()\-]{6,}\d)`)
)

// SpeechNormalizationVersion is part of every synthesized-prompt cache key.
// Increment it whenever the text sent to Piper changes without the source
// prompt itself changing, so a deployment cannot reuse audio generated by an
// older pronunciation policy.
const SpeechNormalizationVersion = 1

var speechTokenReplacements = []struct {
	pattern *regexp.Regexp
	text    string
}{
	// Brand and ordinary words must not be handed to Piper as mixed-case or
	// all-capital tokens: espeak-ng commonly interprets those as letter names.
	{regexp.MustCompile(`(?i)\bvox\s*mail\b`), "Vox Mail"},
	{regexp.MustCompile(`(?i)\bpin\b`), "pin"},
	{regexp.MustCompile(`(?i)\bsip\b`), "sip"},
	{regexp.MustCompile(`(?i)\bimap\b`), "eye map"},

	// These are genuine initialisms. Keep their spoken letters explicit so
	// Piper does not collapse them into an unrelated word.
	{regexp.MustCompile(`(?i)\bhttps\b`), "H T T P S"},
	{regexp.MustCompile(`(?i)\bhttp\b`), "H T T P"},
	{regexp.MustCompile(`(?i)\bsmtp\b`), "S M T P"},
	{regexp.MustCompile(`(?i)\bdtmf\b`), "D T M F"},
	{regexp.MustCompile(`(?i)\bivr\b`), "I V R"},
	{regexp.MustCompile(`(?i)\btotp\b`), "T O T P"},
	{regexp.MustCompile(`(?i)\bapi\b`), "A P I"},
	{regexp.MustCompile(`(?i)\burl\b`), "U R L"},
	{regexp.MustCompile(`(?i)\buuid\b`), "U U I D"},
	{regexp.MustCompile(`(?i)\buidvalidity\b`), "U I D validity"},
	{regexp.MustCompile(`(?i)\buid\b`), "U I D"},
	{regexp.MustCompile(`(?i)\bid\b`), "I D"},
	{regexp.MustCompile(`(?i)\btcp\b`), "T C P"},
	{regexp.MustCompile(`(?i)\budp\b`), "U D P"},
	{regexp.MustCompile(`(?i)\btls\b`), "T L S"},
	{regexp.MustCompile(`(?i)\brtp\b`), "R T P"},
	{regexp.MustCompile(`(?i)\bpcm\b`), "P C M"},
	{regexp.MustCompile(`(?i)\bwav\b`), "W A V"},
	{regexp.MustCompile(`(?i)\bstt\b`), "S T T"},
	{regexp.MustCompile(`(?i)\btts\b`), "T T S"},
	{regexp.MustCompile(`(?i)\bdns\b`), "D N S"},
}

// NormalizeForSpeech converts application text into pronunciation-friendly
// plain text immediately before it reaches Piper. It is deliberately a
// conservative vocabulary, rather than a rule that spells every capitalized
// word: all-caps email prose such as "IMPORTANT" must remain a word.
//
// EmailToSpeech runs first so URLs and addresses are expanded before tokens
// such as HTTP are considered. The operation is idempotent, which matters
// because email bodies may already have passed through EmailToSpeech.
func NormalizeForSpeech(input string) string {
	input = EmailToSpeech(input)
	for _, replacement := range speechTokenReplacements {
		input = replacement.pattern.ReplaceAllString(input, replacement.text)
	}
	return strings.TrimSpace(spaceRE.ReplaceAllString(input, " "))
}

// EmailToSpeech converts common technical tokens to words without exposing
// raw tracking URLs. It deliberately remains deterministic and local.
func EmailToSpeech(input string) string {
	input = html.UnescapeString(input)
	input = garbageRE.ReplaceAllString(input, " ")
	input = anchorRE.ReplaceAllString(input, "link $1")
	input = tagRE.ReplaceAllString(input, " ")
	input = urlRE.ReplaceAllString(input, " link ")
	input = emailRE.ReplaceAllStringFunc(input, spellEmail)
	input = percentRE.ReplaceAllString(input, `$1 percent`)
	input = currencyRE.ReplaceAllStringFunc(input, speakCurrency)
	input = phoneRE.ReplaceAllStringFunc(input, groupDigits)
	input = spaceRE.ReplaceAllString(input, " ")
	return strings.TrimSpace(input)
}

func spellEmail(value string) string {
	value = strings.ToLower(value)
	value = strings.ReplaceAll(value, "@", " at ")
	value = strings.ReplaceAll(value, ".", " dot ")
	value = strings.ReplaceAll(value, "-", " dash ")
	value = strings.ReplaceAll(value, "_", " underscore ")
	return value
}

func speakCurrency(raw string) string {
	kind := map[string]string{"$": "dollars", "€": "euros", "£": "pounds"}
	symbol, width := "", 0
	if first, size := utf8.DecodeRuneInString(raw); first != utf8.RuneError || size > 1 {
		symbol, width = string(first), size
	}
	if width == 0 {
		return raw
	}
	body := raw[width:]
	if i := strings.IndexAny(body, ".,"); i >= 0 {
		major := strings.ReplaceAll(body[:i], ",", " ")
		minor := strings.TrimLeft(body[i+1:], "0")
		if minor == "" {
			return major + " " + kind[symbol]
		}
		return major + " " + kind[symbol] + " and " + minor + " cents"
	}
	return strings.ReplaceAll(body, ",", " ") + " " + kind[symbol]
}

func groupDigits(value string) string {
	var b strings.Builder
	for _, r := range value {
		if r >= '0' && r <= '9' {
			b.WriteRune(r)
			b.WriteByte(' ')
		} else if r == '+' {
			b.WriteString(" plus ")
		}
	}
	return b.String()
}
